### ISSUE TITLE
System install & brightness meter not accurate

### ISSUE THREAD

**Issue by johnny-mac** [LordAmit/Brightness#109]
OS: Linux 
Distro: Void

Hi, how do I do a system install so I can launch this from my menu? I don't run Debian so I can't apt install it... having to cd into the file & running a command isn't really ideal, I'd like it to install so it can be launched from the menu...

And something else I noticed, when I launched it it showed the brightness meter at the top - maxed out, but for some reason I could still increase the brightness with the keyboard buttons.. so I have to have my brightness maxed out when I start the program, otherwise it doesn't give me an accurate measure of brightness...

**Comment by LordAmit** [comment]
Hi,
As far as I know, each major Linux distros has its own way of managing menu items. As a result, I do not think it is possible to create a uniform approach for installing menu items in all Linux Distros. Particularly, I do not know about Void. Maybe you can try going through Void help files to let us know how it can be done? 

About keyboard buttons - the Brightness Controller is a software-based dimmer, whereas the keyboard buttons are generally used for controlling brightness through hardware. So these two works independently. 

Just to clarify, even if you restart the application after lowering brightness, it will start at max value. Currently, it does not save set values and hence it starts at default, i.e. max value. 

Hope this helps :smile:

**Comment by apandada1** [comment]
To launch it from menu, make a .desktop file that will execute the
'init.py'. Add icon as well. Now place the .Desktop file in the hidden
folder (in your home folder) '.local/share/application'. If it still does
not show up in menu, restart your computer.
On Apr 15, 2018 9:35 PM, "Amit Seal Ami" <notifications@github.com> wrote:

Hi,
As far as I know, each major Linux distros has its own way of managing menu
items. As a result, I do not think it is possible to create a uniform
approach for installing menu items in all Linux Distros. Particularly, I do
not know about Void. Maybe you can try going through Void help files to let
us know how it can be done?

About keyboard buttons - the Brightness Controller is a software-based
dimmer, whereas the keyboard buttons are generally used for controlling
brightness through hardware. So these two works independently.

Just to clarify, even if you restart the application after lowering
brightness, it will start at max value. Currently, it does not save set
values and hence it starts at default, i.e. max value.

Hope this helps 😄

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LordAmit/Brightness/issues/109#issuecomment-381417583>,
or mute the thread

**Comment by AdamKane41** [comment]
My **modified** ".desktop" file on Ubuntu 18.04 (Using VGA-1):
![peek 2018-04-26 17-41](https://user-images.githubusercontent.com/30092603/39333938-bfa1ce86-497a-11e8-85b2-e25bad7b00ac.gif)

/usr/share/applications/brightness-controller.desktop

```
[Desktop Entry]
Name=Brightness Controller
Comment=Adjust your screen brightness easily
Icon=brightness-controller
Exec=brightness-controller
Terminal=false
Type=Application
Categories=Utility
StartupNotify=true
Name[en_US]=Brightness Controller

Actions=Default;1900K Candle;2600K 40W Tungsten;2850K 100W Tungsten;3200K Halogen;5200K Carbon Arc;5400K High Noon;6000K Direct Sun;7000K Overcast Sky;20000K Clear Blue Sky;
[Desktop Action Default]
Name=Default
Exec=xrandr --output VGA-1 --gamma 0.99:0.99:0.99 --brightness 0.99
[Desktop Action 1900K Candle]
Name=1900K Candle
Exec=xrandr --output VGA-1 --gamma 0.99:0.57:0.16 --brightness 0.99
[Desktop Action 2600K 40W Tungsten]
Name=2600K 40W Tungsten
Exec=xrandr --output VGA-1 --gamma 0.99:0.77:0.56 --brightness 0.99
[Desktop Action 2850K 100W Tungsten]
Name=2850K 100W Tungsten
Exec=xrandr --output VGA-1 --gamma 0.99:0.83:0.66 --brightness 0.99
[Desktop Action 3200K Halogen]
Name=3200K Halogen
Exec=xrandr --output VGA-1 --gamma 0.99:0.94:0.87 --brightness 0.99
[Desktop Action 5200K Carbon Arc]
Name=5200K Carbon Arc
Exec=xrandr --output VGA-1 --gamma 0.99:0.98:0.95 --brightness 0.99
[Desktop Action 5400K High Noon]
Name=5400K High Noon
Exec=xrandr --output VGA-1 --gamma 0.99:0.99:0.98 --brightness 0.99
[Desktop Action 6000K Direct Sun]
Name=6000K Direct Sun
Exec=xrandr --output VGA-1 --gamma 0.99:0.99:0.99 --brightness 0.99
[Desktop Action 7000K Overcast Sky]
Name=7000K Overcast Sky
Exec=xrandr --output VGA-1 --gamma 0.99:0.78:0.88 --brightness 0.99
[Desktop Action 20000K Clear Blue Sky]
Name=20000K Clear Blue Sky
Exec=xrandr --output VGA-1 --gamma 0.25:0.61:0.99 --brightness 0.99

```

Peace!
