### ISSUE TITLE
Brightness Controller disabled on iMac

### ISSUE THREAD

**Issue by tsalemi** [LordAmit/Brightness#124]
**Describe the bug**
Installed brightness controller on Ubuntu 18.04.1.

**To Reproduce**
1. Install Brightness Controller and open it
2. Note that primary brightness and secondary brightness are disabled

**Expected behavior**
Expect to be able to change the brightness

**Screenshots**
http://ubuntuhandbook.org/wp-content/uploads/2017/05/brightness-controller-600x319.jpg

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1

**Additional context**
xrandr: Failed to get size of gamma for output default
Screen 0: minimum 2560 x 1440, current 2560 x 1440, maximum 2560 x 1440
default connected primary 2560x1440+0+0 0mm x 0mm
   2560x1440     93.00* 

Apple iMac "Core i7" 2.8 27-Inch (Late 2009) 
Have disabled Radeon graphics card
/sys/class/backlight is empty

**Comment by LordAmit** [comment]
Hi,

Those were supposed to be disabled when you have only one display connected. The drop downs are used to assign Primary and Secondary attributes on your displays so that you get a flexible control over them. 

Based on your xrandr output, it seems like you have only one display - so it should be behaving as expected. Unless you have multiple displays?

Did you try moving the sliders under Primary?

**Comment by tsalemi** [comment]
I have only one display and moving the sliders does not work
