### ISSUE TITLE
iMac Ubuntu Brightness control issue

### ISSUE THREAD

**Issue by tsalemi** [LordAmit/Brightness#130]
**Describe the bug**
Installed brightness controller on Ubuntu 18.04.1.

**To Reproduce**

1. Install Brightness Controller and open it
2. Note that primary brightness and secondary brightness are disabled

**Expected behavior**
Expect to be able to change the brightness

**Screenshots**
http://ubuntuhandbook.org/wp-content/uploads/2017/05/brightness-controller-600x319.jpg

**Desktop (please complete the following information):**

* OS: Ubuntu 18.04.1

**Additional context**
xrandr: Failed to get size of gamma for output default
Screen 0: minimum 2560 x 1440, current 2560 x 1440, maximum 2560 x 1440
default connected primary 2560x1440+0+0 0mm x 0mm
2560x1440 93.00*

Apple iMac "Core i7" 2.8 27-Inch (Late 2009)
Have disabled Radeon graphics card
/sys/class/backlight is empty
Moving the sliders does not work

**Comment by joeSIX** [comment]
I have the exact same issue.

**Comment by LordAmit** [comment]
Hmm..
The labels get disabled when only one display is detected through xrandr, while the vertical sliders are usable for only the primary display. It is designed to work this way because those drop down options are only there to assign primary/secondary display labels to different screens arbitrarily. 
Without a second display, such features become unnecessary, unapplicable, and therefore, disabled.
 
As shown in xrandr log - there is only one screen detected. 

If there are indeed multiple devices connected, and xrandr shows only one connected screen - please report to xrandr.

If you have only one display connected - then Brightness Controller is working as intended.
