### ISSUE TITLE
instructions please

### ISSUE THREAD

**Issue by leytanelectronics2** [LordAmit/Brightness#140]
it would be super helpful if we could get instructions on how to use this program, like how to run it, how to assign it to a desktop icon, how to set it up, all of this would be wonderful, but there is nothing to show us what to do or how the thing even works. please include some instructions for stupid people like me to follow.

**Comment by LordAmit** [comment]
Due to the different types of Linux Distros out there, it is near impossible to give a single howto that applies to all of them. So we only provide the minimal instructions in the readme, that are applicable across distros and help people out through issues. 

We are expecting to change that in the new version of Brightness Controller, where it will be installable using alternative methods.

Which Distro are you using, and how are you trying to install it? We can start from there. :)

**Comment by apandada1** [comment]
@leytanelectronics2 What is your operating system?
