### ISSUE TITLE
Please add support for OLED displays

### ISSUE THREAD

**Issue by brianfinley** [LordAmit/Brightness#175]
As OLED displays don't support brightness adjustment by increasing/decreasing the backlight level (they have no backlight), a different method is needed to adjust their brightness (such as xrandr with the "--brightness" option).  Would love to be able to use this tool with my OLED displays.

**Comment by LordAmit** [comment]
Hi!

Thanks for the suggestion. 

To make sure that I am understanding you right, however, I need to ask this:

By different method - did you mean that xrandr with --brightness is the different method (which should be sued), or a different method is required because xrandr --brightness won't work for OLED based displays?

**Comment by brianfinley** [comment]
Hi LordAmit,

Sorry for the delayed response.  xrandr --brightness _is_ a different method that works with OLED based displays.

**Comment by apandada1** [comment]
@brianfinley We have been using `xrandr --brightness` in the app. Does it not work? Are you in a Wayland session?

**Comment by brianfinley** [comment]
It did not work at the time I submitted the initial request.  I created my own hacky command to do it using `xrandr --brightness`.

My distro (Ubuntu 20.04) now supports it natively (simple brightness adjustment only), but I re-installed brightness-controller via the PPA and tested to give you a good answer.  Turns out brightness-controller is also working now, and it's quite nifty to be able to control my built-in and external monitor from the same panel. :-)

If this part of the code hasn't changed since my initial report, then perhaps it's working now because something that was b0rken in the distro has been fixed?  Not sure, but looks like we're all good now.

Thanks!

**Comment by apandada1** [comment]
The ppa was last updated in April. It's good to hear that it's working as intended.

**Comment by LordAmit** [comment]
Thank you for getting back to us @brianfinley :) Really glad to know that you went through the extra miles to give us a solid answer with Ubuntu 20.04.

The code has indeed changed over time. I do not think that helped it fix though since I don't remember touching the core functionality of Brightness Controller. But 🤷‍♂️. 

I am glad that it is working. :)
