### ISSUE TITLE
Doesn't work for Ubuntu 20 with Wayland

### ISSUE THREAD

**Issue by marimeireles** [LordAmit/Brightness#177]
To reproduce open brightness:

![image](https://user-images.githubusercontent.com/17600982/91354968-02dc4480-e7dd-11ea-8ec8-9008384dc32d.png)

When you try to apply any settings, nothing changes.

**Comment by apandada1** [comment]
Are you on a Wayland session?

**Comment by marimeireles** [comment]
Yes.

**Comment by marimeireles** [comment]
Do you have any clue on why? Maybe I could try to look it up.

**Comment by apandada1** [comment]
@marimeireles  Brightness Controller uses [`xrandr`](https://wiki.archlinux.org/index.php/Xrandr) in the backend, which is a xorg utility.
@LordAmit Eventually every distro will frop xorg, so we need to put Wayland support in the todo list, and keep this issue open.

**Comment by apandada1** [comment]
@marimeireles Does Ubuntu 20.04 use Wayland by default?

**Comment by LordAmit** [comment]
@apandada1 - Wayland support will only be possible if it allows controlling brightness, which as far as I know, is not possible till now. Probably one of the many issues why Ubuntu went back to using xorg by default instead of Wayland during 18.04. In other words, unless Wayland becomes mature/some other display protocol is mature enough to replace xorg - we can not/should not really do much from our side. 

Can you please provide a reference to "Eventually every distro will drop xorg"?
I'd close this issue later and create a different issue as future-goal since this issue deals with a separate concern.

**Comment by apandada1** [comment]
I found that they would maintain backward compatibility with X.Org, even if they switch to Wayland when it is stable enough. So they won't probably completely drop X.Org. https://wiki.ubuntu.com/Wayland

However I have a suspicion that when Wayland is mature enough, the default installation may not contain X.Org anymore, just like what happened with Python2 or GNOME 2 (both of these worked very well when they were deprecated). It may still take many years, though.

**Comment by marimeireles** [comment]
>@marimeireles Does Ubuntu 20.04 use Wayland by default?

@apandada1 I don't think so, I was just curious about waylander cause I started to have a look in their project a while ago, so wanted to try.
They still didn't implement this kind of thing yet? Are you sure? If not I can try to look it up or ask in their channels.

& thanks for the response people! 🌸

**Comment by LordAmit** [comment]
As far as I know, unfortunately no. Of course, if you can find a way (either through them or etc) we will be really glad. Supporting wayland is one of the most requested features we have received. Thank you for being so helpful. 🙏
