### ISSUE TITLE
Support for rpm based distros?

### ISSUE THREAD

**Issue by Alex-Samari** [LordAmit/Brightness#181]
Is there or will there be support for rpm based distros? (Mainly Fedora and openSUSE)

**Comment by apandada1** [comment]
<h2>This is how to use it in any distro</h2>

Being written in Python, Brightness Controller supports almost all GNU/Linux distributions. You can certainly run it from the source in Fedora or openSUSE. Install Pyside2, and and run `python3 src/init.py`. For convenience, you can also create a desktop file or modify [this template](https://github.com/LordAmit/Brightness/blob/releases/usr/share/applications/brightness-controller.desktop).

<h2>Native package for rpm based distros</h2>

We cannot provide support for a native installer for rpm based systems due to lack of experience with rpm based distros.
However, if anyone comes up with a working rpm package/repository and wants to maintain it, we would be happy to acknowledge their contribution, and include it in the Readme.

I created an experimental rpm package from the deb package using Alien. Kindly let us know if it works. Not being an Fedora user, I could not test it, so _use at your own risk_. Also note that Brightness Controller does not work in Wayland. In case this package does not work, try installing Pyside2 manually.
**Rename** the file from `brightness-controller-2.3.4-1.noarch.rpm.zip` --> `brightness-controller-2.3.4-1.noarch.rpm` (otherwise GitHub won't let me upload it). Do not try to extract the .zip.

[brightness-controller-2.3.4-1.noarch.rpm.zip](https://github.com/LordAmit/Brightness/files/5628356/brightness-controller-2.3.4-1.noarch.rpm.zip)

**Comment by Alex-Samari** [comment]
@apandada1 

Thanks for the detailed reply and sorry for the late reply. I did manage to run it from source but since I need to use Wayland, Brightness Controller wouldn't be a good option for me.
