### ISSUE TITLE
Feature Request: Flatpak support

### ISSUE THREAD

**Issue by seth100** [LordAmit/Brightness#182]
Would it be possible to publish a version of this software as Flatpak package?
At the moment I prefer not to install it from PPA or source code, but I would install it if it was available via Flatpak.

Thanks

**Comment by apandada1** [comment]
At the moment we cannot support Flatpak due to lack of time. If someone comes up with a Flatpak, we would be happy to enlist it in the README (if anyone is interested - first the `setup.py` has to be properly configured. That would help both Flatpak/Snap and Debian packaging. Also, with a proper `setup.py` we can publish the tool to PyPI).

@seth100 Did you face any issue with the PPA/.deb file or the running it from the source? The methods are well documented in the README, and are not supposed to break your system, if that's why you wanted to use a flatpak.

**Comment by seth100** [comment]
> @seth100 Did you face any issue with the PPA/.deb file or running it from the source? If you use a .desktop file then you won't have to run it from Terminal. The methods are well documented in the README, and are not supposed to break your system, if that's why you wanted to use a flatpak.

it's just a matter of not wanting to add a PPA to my system.
Anyway, thanks I hope someone will be able to add support for it so that I will be able to use it!

**Comment by apandada1** [comment]
> it's just a matter of not wanting to add a PPA to my system.

Then you can use the [.deb](https://launchpad.net/~apandada1/+archive/ubuntu/brightness-controller/+files/brightness-controller_2.3.4-0~202004260413~ubuntu20.04.1_all.deb)
