### ISSUE TITLE
Does not work on 21.04

### ISSUE THREAD

**Issue by zawedcvg** [LordAmit/Brightness#189]
**Describe the bug**
Doesn't work ever since i updated ubuntu to 21.04.(have installed all the requirements)

**To Reproduce**
Update to ubuntu 21.04
**Expected behavior**
The panel appears like before however no change in brightness.

**Screenshots**

**Desktop (please complete the following information):**
- Dual booted ubuntu with windows.

**Additional context**
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
getting this error on running brightness-controller

xrandr -q output
Screen 0: minimum 16 x 16, current 1920 x 1080, maximum 32767 x 32767
XWAYLAND0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 340mm x 190mm
   1920x1080     59.96*+
   1440x1080     59.87  
   1400x1050     59.86  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.78  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   720x480       59.71  
   640x400       59.20  
   320x200       58.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77

**Comment by apandada1** [comment]
Ubuntu 21.04 uses Wayland by default, and this tool does not support Wayland. Switch to the X.Org session, to use this tool.

By the way, could you check whether redshift work in Wayland?

**Comment by apandada1** [comment]
This tool uses `xrandr` as a backend, and AFAIK, there is no equivalent of it in Wayland (See https://askubuntu.com/q/1286458/124466).

Redshift is another tool for changing brightness and color temperature. I don't know if it uses `xrandr` or something else. That is why, would be useful to know if it works in Wayland.
See https://www.linuxandubuntu.com/home/redshift-control-display-color-temperature (this link talks about setting location manually, but usually redshift automatically finds your approximate location from the internet).

> any plans to support wayland in the future?

We are quite busy due to huge workload in universities. We don't know when we would get time to implement it.

**Comment by LordAmit** [comment]
Hi @zawedcvg , thanks for the report. 

To clarify, we will be able to support `wayland` when `wayland` offers a mechanism / API to change brightness (and other properties). As far as we know, there simply is not any. We are on the lookout, of course. :)

**Comment by NaNraptor** [comment]
Came here to say Im on ubuntu 21.10 with the 16.14 kernel (manually updated kernel to this latest version). The app seems to change brightness for a second then after I let go of the slider it changes back to full brightness. Of course Im on wayland since it is a default
