### ISSUE TITLE
Modifying brightness of external monitor stops Ubuntu's night light only on that monitor

### ISSUE THREAD

**Issue by Josee9988** [LordAmit/Brightness#192]
**Describe the bug**
When I modify the brightness of one of my external monitors it suddenly stops having the night light but only in that specific monitor. I always use the built-in ubuntu night lights and if I modify the brightness of the external monitor then I need to restart the night light to make it appear again, so that is kind of a mess.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set ubuntu's night light on
2. Modify the brightness of the external monitor
3. The modified monitor will no longer have the night light on.

**Expected behaviour**
To maintain the night light in my monitor even if I modify the brightness

**Screenshots**
I link a video exaggerating my night light warmness so you can easily see what I mean.
In the video, you can see how the night lights disappear only for that monitor when the brightness is adjusted while the other external monitor and the main display maintain the night light on.

https://user-images.githubusercontent.com/38838976/119253254-ad3c9900-bbb0-11eb-888f-06a0da3034d4.mp4

I don't know if that might be a problem with the OS or an issue with your program. Anyways this makes it unusable for me :(

**Desktop (please complete the following information):**
 - Ubuntu 20.04.2 LTS x86_64

**Additional context**
Add any other context about the problem here. Typically, the output of `xrandr -q`.

```text
$ xrandr -q
Screen 0: minimum 8 x 8, current 5760 x 1080, maximum 32767 x 32767
HDMI-0 connected 1920x1080+3840+0 (normal left inverted right x axis y axis) 480mm x 270mm
   1920x1080     60.00*+  59.94    50.00    60.05    60.00    50.04  
   1680x1050     59.95  
   1600x900      60.00  
   1440x900      59.89  
   1400x1050     59.98  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-0 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 521mm x 293mm
   1920x1080     60.00 +  74.92*   59.94    50.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1440x900      59.89  
   1440x576      50.00  
   1440x480      59.94  
   1400x1050     59.98  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      59.94    50.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  
DP-1 disconnected (normal left inverted right x axis y axis)
eDP-1-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 382mm x 215mm
   1920x1080     60.00*+  59.97    59.96    59.93  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
  1680x1050 (0x1c4) 146.250MHz -HSync +VSync
        h: width  1680 start 1784 end 1960 total 2240 skew    0 clock  65.29KHz
        v: height 1050 start 1053 end 1059 total 1089           clock  59.95Hz
  1280x1024 (0x1c9) 108.000MHz +HSync +VSync
        h: width  1280 start 1328 end 1440 total 1688 skew    0 clock  63.98KHz
        v: height 1024 start 1025 end 1028 total 1066           clock  60.02Hz
  1440x900 (0x1c6) 106.500MHz -HSync +VSync
        h: width  1440 start 1520 end 1672 total 1904 skew    0 clock  55.93KHz
        v: height  900 start  903 end  909 total  934           clock  59.89Hz
  1280x960 (0x1dd) 108.000MHz +HSync +VSync
        h: width  1280 start 1376 end 1488 total 1800 skew    0 clock  60.00KHz
        v: height  960 start  961 end  964 total 1000           clock  60.00Hz
  1280x800 (0x1ca) 83.500MHz -HSync +VSync
        h: width  1280 start 1352 end 1480 total 1680 skew    0 clock  49.70KHz
        v: height  800 start  803 end  809 total  831           clock  59.81Hz
  1024x768 (0x1d0) 65.000MHz -HSync -VSync
        h: width  1024 start 1048 end 1184 total 1344 skew    0 clock  48.36KHz
        v: height  768 start  771 end  777 total  806           clock  60.00Hz
  800x600 (0x1d2) 40.000MHz +HSync +VSync
        h: width   800 start  840 end  968 total 1056 skew    0 clock  37.88KHz
        v: height  600 start  601 end  605 total  628           clock  60.32Hz
  800x600 (0x1e0) 36.000MHz +HSync +VSync
        h: width   800 start  824 end  896 total 1024 skew    0 clock  35.16KHz
        v: height  600 start  601 end  603 total  625           clock  56.25Hz
  640x480 (0x1d6) 25.175MHz -HSync -VSync
        h: width   640 start  656 end  752 total  800 skew    0 clock  31.47KHz
        v: height  480 start  490 end  492 total  525           clock  59.94Hz
```

Thanks

**Comment by LordAmit** [comment]
Hello!  Thanks for the detailed report and the video. Really, really appreciate your effort in making this as detailed as possible. 

Night light (by ubuntu, or by other third party like f.lux) and Brightness Controller don't play nice with each other nicely at present because of several reasons. One of them is basically, not being aware of changes being made by each of them separately and overwriting everything altogether.

But in the case of Night Light, it might (or might not) be solvable. I need to understand a bit more about Night Light though. What happens when you do the following? 

- Modify the brightness of the external monitor
- Set ubuntu's night light on

Does it also reset the brightness? Or it just changes the temperature?

**Comment by Josee9988** [comment]
It resets the brightness as well.

**Comment by LordAmit** [comment]
Oh, that's sad. That means it will not be possible to solve this issue, at least not at present. Let me try to elaborate.

Ubuntu's night light is treating the temperature and brightness as an exclusive resource. I really don't see any way which will allow Brightness Controller to co-exist with other apps, even though it can be built to do so, because other apps will simply overwrite whatever Brightness Controller does.

Moreover, building  Brightness Controller to not handle brightness and temperature exclusively will mean that it will have to either a) continuously pull the latest settings related to Brightness and Temperature every time we change (like dragging the slider), or b) the resources will have to push events that can be received by third party apps like Brightness Controller.

a) will be very resource intensive (will end up creating visible lag between changing brightness and dragging slider --> reduced  usability) and b) is out of Brightness Controller's hand (has to be from the OS's side).

Overall, I do not see any way to solve this issue. Let me know if this helps, or if you know of something that might help solve this. 😅

**Comment by Josee9988** [comment]
Ow, what a pity 😢
Thanks anyway for the fast response, the interest and the great program you've built.
Cheers ❤️

**Comment by apandada1** [comment]
@Josee9988 Does the GNOME night light work on Wayland? Brightness Controller does not work on Wayland (the `xrandr` back-end is only supported in X.Org). But if night light works with Wayland, then there may be a way to make this program Wayland compatible.

**Comment by Josee9988** [comment]
@apandada1 Yes it does work on Wayland, as far as I know, but right now I'm using XORG as you can see in the image
![image](https://user-images.githubusercontent.com/38838976/120098006-de2e4800-c133-11eb-9e50-5c6493cbd7e8.png)
