### ISSUE TITLE
How I handle on Debian 12

### ISSUE THREAD

**Issue by Jasdent** [LordAmit/Brightness#249]
1. `sudo apt-get install python3-launchpadlib` install this or launchpad source will not be deemed as a legit source 
2. `sudo add-apt-repository ppa:apandada1/brightness-controller` works
3. `sudo apt install brightness-controller` works perfectly

**Comment by archisman-panigrahi** [comment]
Debian recommends that you don't add a PPA. Instead, manually download and install the .deb file from Launchpad

**Comment by JooDye** [comment]
Update: I used this script on another instance of debian 12,
`sudo add-apt-repository ppa:apandada1/brightness-controller` is no longer reliable because I got prompted with `E: The repository 'https://ppa.launchpadcontent.net/apandada1/brightness-controller/ubuntu bookworm Release' does not have a Release file.`

adding a source list file with the following content will resolve it.
```
# apandada1-ubuntu-brightness-controller-bookworm.list
deb https://ppa.launchpadcontent.net/apandada1/brightness-controller/ubuntu/ jammy main
# deb-src https://ppa.launchpadcontent.net/apandada1/brightness-controller/ubuntu/ bookworm main
```

**Comment by archisman-panigrahi** [comment]
PPAs don't work in debian unless you properly add an entry to `sources.list` (which is not recommended by Debian developers, see https://wiki.debian.org/DontBreakDebian). 

Consequently there is no version corresponding to bookworm.


Instead of adding the ppa, download the deb package from launchpad and
install it.
