### ISSUE TITLE
link to source code zip broken

### ISSUE THREAD

**Issue by audi4kq** [lordamit/Brightness#72]
Under v2 Beta source code page is the step for retrieving the zip "Next, download the latest zip file from here," given as https://github.com/lordamit/Brightness/archive/develop.zip and returns a 404. 

It's a great utility and appreciate its availability. I used v1.2.2 again without incident. Not sure why the Software Center doesn't pull the respective link either (maybe because I'm on Kubuntu 16?). Nothing else does what this little program does. So thank you.

**Comment by lordamit** [comment]
Hi,
Link is being fixed. :smile:  Thank you for letting us know about it. 

The software center does not know about the Brightness Controller because Ubuntu changed things and we can not currently push it to the software center after Ubuntu 14.04. There is a PPA, which is for version 1 maintained by @apandada1  I think. 

I am really glad that you found the program useful :+1:
